name: firmware-ESP32 build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature/icsc21

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git submodule update 
      run: git submodule update --init --recursive
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev libsdl2-dev  dfu-util libusb-1.0-0 libncurses5-dev libncursesw5-dev
    - name: Install Python requirements for build scripts
      run: pip3 install -r requirements.txt
    - name: Install Python requirements for esp-idf
      run: pip3 install --user -r esp-idf/requirements.txt
    - name: Unzip toolchain
      run: unzip -p toolchain/xtensa-esp32-elf-linux64.zip xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar | tar xvf -
    - name: Build
      run: ./build.sh
